### PR TITLE
update for Julia v0.7

### PR DESCRIPTION
**Pull request by RalphAS**

### CODE REVIEW

**Comment by mschauer** [comment]
Thank you! In the PR the new naming convention for exported functions is `vlog(a)` and `log!(a)` ( to avoid conflicts with base). Just to mention, https://github.com/JuliaMath/Yeppp.jl in a similar niche uses 
`Yeppp.log` and `Yeppp.log!`.

**Comment by mschauer** [comment]
Related older issue tracking consistency of interfaces over there: https://github.com/JuliaMath/Yeppp.jl/issues/9

**Comment by KristofferC** [comment]
FWIW, I like prefixing with the module name.

**Comment by RalphAS** [comment]
Ok, to make the interface consistent with others I'll switch to `VML.log, VML.log!` etc. and stop exporting the bindings.  Revision in progress.

**Comment by mschauer** [comment]
Actually, maybe it is good to discuss this first. I like the module-name prefix too. On the other hand, using a function `vlog` and `vlog!` means that code is oblivious to which packages actually provides these functions and switching `VML` with `Yeppp` eg becomes easier.

**Comment by RalphAS** [comment]
An alternative would be an umbrella package which aliases the bindings of whichever one is installed, maybe managed by Requires.jl

**Comment by Djoop** [comment]
Maybe the PR should be merged so that the package can be installed on julia≥0.7, keeping the creation of an umbrella package an option for the future? 
I personally like prefixing with the module name, and given that e.g. Yeppp and VML export different subsets of functions I'm not convinced that a separate package would really make the choice cleaner (but I might be wrong!).

**Comment by aminya** [comment]
This should be closed because there is another PR for Julia 1: https://github.com/JuliaMath/VML.jl/pull/17

**Comment by aminya** [comment]
@ViralBShah Please close this as it is not applicable anymore.

**Pull request closed without merging**
